### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ojvribeiro** [ojvribeiro/win10-vulmix#1]
- [ ] Taskbar
  - [ ] Volume control
  - [ ] Network status
  - [x] Date and Hour
    - [ ] Calendar
  - [ ] Gesture controls
    - [ ] Drag and drop
    - [ ] Swipe up for context menu
    - [ ] Hover on screen bottom-left corner to show Desktop view
  - [ ] Start menu
    - [ ] App list
    - [ ] App grid
    - [ ] Options
    - [ ] Gesture controls
      - [ ] Drag and drop
  - [ ] Task view
  - [x] App icons
  - [ ] News and interests
  - [ ] Hidden icons
- [ ] App window
  - [ ] Classic
  - [ ] Fluent (UWP)
  - [ ] Window options
    - [ ] Minimize
    - [ ] Restore
    - [ ] Close
  - [ ] Window title (if needed)
- [ ] Desktop
  - [ ] Context menu
  - [ ] Gesture controls
    - [ ] Drag and drop
- [ ] Default Apps
  - [ ] Calc
  - [ ] Terminal
  - [ ] Settings
  - [ ] Store
  - [ ] Notepad
  - [ ] Trash
  - [ ] Clock
